### 8. Create a 10 × 10 array of random integers. Find the indices of the maximum value in the array and replace that specific value with −1 without using a loop.

In [8]:
import numpy as np
arr = np.random.randint(1,100,(10,10))
idx = np.unravel_index(np.argmax(arr), arr.shape)
arr[idx] = -1
print(arr)

[[21 94 82 20 89 87 19  7  2 56]
 [ 4 14 34 21  4 98 31 29 20 81]
 [ 5 36  9 88 53 15 10 92 79 67]
 [49 90 38 43 34  4 31 80 -1 21]
 [17 78 66 89 72 17 80 53 48 86]
 [74 59 41 50 80 16  8 99 64 43]
 [52 48 91 37 27 28 32 78 14 47]
 [96 27 33 24 59 24 14  5 48  5]
 [86 12 65 74  5  5 64 32 71 50]
 [43 17 65 93 41  8 42 71 30 59]]
