### 2. Create the following arrays:
#### a) zeros matrix of shape (4,4)
#### b) identity matrix of size 5
#### c) random array of size 10

In [ ]:
import numpy as np
zero_arr = np.zeros((4,4))
print("Zero Matrix", zero_arr)
identity_arr = np.eye(5)
print("identity matrix \n", identity_arr)
rand_arr = np.random.random(10)
print("Random Array",rand_arr)

Zero Matrix [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
identity matrix
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Random Array [0.42548608 0.37309841 0.27206314 0.05920997 0.04795186 0.04977172
 0.50669186 0.47327929 0.46061813 0.75012763]
