### 10. You have two arrays representing coordinates: 𝐴 = (𝑛, 2) and 𝐵 = (𝑚, 2). Calculate the Euclidean distance between every pair of points in 𝐴 and 𝐵 without using a single for loop.

In [6]:
import numpy as np
A = np.random.rand(3,2)
B = np.random.rand(4,2)

distances = np.sqrt(((A[:, None, :] - B[None, :, :]) ** 2).sum(axis=2))
print(distances)

[[0.54538192 0.65914627 0.30426479 0.18388385]
 [0.15908785 0.33661456 0.5941928  0.46124758]
 [0.31758741 0.41807602 0.90312201 0.78915919]]
