### 20. Demonstrate NumPy broadcasting with a clear example.

#### “NumPy broadcasting allows arithmetic operations on arrays of different shapes by automatically expanding the smaller array along compatible dimensions, without copying data or using loops.”

In [1]:
import numpy as np
import pandas as pd
a = np.array([[1],[2],[3]])
b = np.array([10,20,30])

print(a + b)


[[11 21 31]
 [12 22 32]
 [13 23 33]]
