### 11. Experiment with weight initialization. Compare the training progress of a deep network (5+ layers) when weights are initialized to all zeros and large random numbers. Observe and document the "vanishing gradient" problem.

## Small Demonstration Code

### Zero Initialization Example

In [4]:
import numpy as np

X = np.random.randn(5,3)
W = np.zeros((3,4))

Z = X @ W
print("Output with zero weights:\n", Z)

Output with zero weights:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### All outputs identical → no learning diversity.

## Large Initialization Example

In [8]:
W_large = np.random.randn(3,4) * 100

Z_large = X @ W_large
print("Large activations:\n", Z_large)

Large activations:
 [[-122.03396667   71.68072206  188.98595211   -7.09614854]
 [  76.4939116  -107.85857936 -143.50023073  -37.29445368]
 [ 104.46908921  410.77473617  110.92411317  -62.38870759]
 [ 190.94780926    3.3025448  -201.80232098 -128.06213532]
 [-142.36641892 -252.62278995   26.8079442    37.99889439]]


### Values become extremely large → sigmoid saturates.

## nitializing all weights to zero causes symmetry, preventing neurons from learning different features. Very large initial weights cause saturation in sigmoid or tanh activations, leading to vanishing gradients. Proper initialization methods such as Xavier and He initialization maintain stable gradient flow and improve training stability in deep neural networks.